#!/usr/bin/python

"""Amulet tests on a basic neutron-openvswitch deployment on utopic-juno."""

from basic_deployment import NeutronOVSBasicDeployment

if __name__ == '__main__':
    deployment = NeutronOVSBasicDeployment(series='utopic')
    deployment.run_tests()
